export const LOGIN_ACTION = 'LOGIN_ACTION'
export const REGISTER_ACTION = 'REGISTER_ACTION'
export const GET_ACTIVITIES_ACTION = 'GET_ACTIVITIES_ACTION'
export const DEPOSIT_ACTION = 'DEPOSIT_ACTION'
export const SEND_MONEY_ACTION = 'SEND_MONEY_ACTION'
export const WITHDRAW_ACTION = 'WITHDRAW_ACTION'
export const WITHDRAW_APPROVAL_ACTION = 'WITHDRAW_APPROVAL_ACTION'
export const WITHDRAW_CANCEL_ACTION = 'WITHDRAW_CANCEL_ACTION'
export const WITHDRAW_RECEIPTS_ACTION = 'WITHDRAW_RECEIPTS_ACTION'
export const DEPOSIT_RECEIPTS_ACTION = 'DEPOSIT_RECEIPTS_ACTION'
export const TRANSFER_RECEIPTS_ACTION = 'TRANSFER_RECEIPTS_ACTION'
export const REMOVE_USER = 'REMOVE_USER'


export const LOADING_ACTION = 'LOADING_ACTION'
export const ERROR_ACTION = 'ERROR_ACTION'

export const SET_BARCODE = 'SET_BARCODE'